const constants = {
	FROM_UFA_TO_CHECKMAGUSH: 0,
	FROM_CHECKMAGUSH_TO_UFA: 1,
	PASSENGER: 10,
	DRIVER: 11,
	TODAY: 20,
	TOMORROW: 21,
	OTHER: 22,
	SET_OTHER: 23,
	STATE_UNDEFINED: -1,
	STATE_SET_TIME: 1,
}

module.exports = constants